// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ2YFc8GUI254f7YBfQYEL_t9IeKMR3Zk',
    appId: '1:85002891621:web:62eb6d8b206f93a7f8718c',
    messagingSenderId: '85002891621',
    projectId: 'mecore-5a9fc',
    authDomain: 'mecore-5a9fc.firebaseapp.com',
    storageBucket: 'mecore-5a9fc.firebasestorage.app',
    measurementId: 'G-L2X8ZD682S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0Tt0bsCgJ0LXrsreQIf7pkHzSKVNKKI',
    appId: '1:85002891621:android:05367a466b7274e6f8718c',
    messagingSenderId: '85002891621',
    projectId: 'mecore-5a9fc',
    storageBucket: 'mecore-5a9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdGFR9CIOuSSgqtAMqeDhy6hs6UZTwTK4',
    appId: '1:85002891621:ios:3924296e2cf90f19f8718c',
    messagingSenderId: '85002891621',
    projectId: 'mecore-5a9fc',
    storageBucket: 'mecore-5a9fc.firebasestorage.app',
    iosBundleId: 'com.hashtagmood.mecore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ2YFc8GUI254f7YBfQYEL_t9IeKMR3Zk',
    appId: '1:85002891621:web:980f6da5356d1628f8718c',
    messagingSenderId: '85002891621',
    projectId: 'mecore-5a9fc',
    authDomain: 'mecore-5a9fc.firebaseapp.com',
    storageBucket: 'mecore-5a9fc.firebasestorage.app',
    measurementId: 'G-ZDC3NK14LZ',
  );

}